apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio11-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio11
  template:
    metadata:
      labels:
        app: desafio11
    spec:
      containers:
        - name: desafio11
          image: 1wil1/desafio11:1
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: MONGO_DB_URI
              value: mongodb://mongodb:27017
            - name: MONGO_DB_NAME
              value: app-desafio11
            - name: MONGO_DB_USER
              value: root
            - name: MONGO_DB_PASS
              value: password
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: desafio11-service
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30002
  selector:
    app: desafio11
