apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: desafio12
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGO_DB_URI
              value: mongodb://{{ .Release.Name }}-mongodb:27017
            - name: MONGO_DB_NAME
              value: {{ .Values.mongo.mongoDatabase }}
            - name: MONGO_DB_USER 
              value: {{ .Values.mongo.mongoUser }}
            - name: MONGO_DB_PASS
              value: {{ .Values.mongo.mongoPassword }}
            - name: PORT
              value: "{{ .Values.service.port }}"
