pipeline {
    agent any
    environment {
        TEMPLATE_FILE = 'Desafio7/ansible/files/index-template.html'
        OUTPUT_FILE = 'Desafio7/ansible/files/index.html'
        INVENTORY_FILE = 'inventory.ini'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Debug') {
            steps {
                script {
                    echo "Branch name: ${env.BRANCH_NAME}"
                }
            }
        }
        stage('Set Environment') {
            steps {
                script {
                    // Definir el ambiente basado en la rama
                    def ambiente
                    if (env.BRANCH_NAME == 'dev') {
                        ambiente = 'Development'
                    } else if (env.BRANCH_NAME == 'staging') {
                        ambiente = 'Staging'
                    } else if (env.BRANCH_NAME == 'main') {
                        ambiente = 'Production'
                    } else {
                        error "No environment defined for branch: ${env.BRANCH_NAME}"
                    }
                    pwd
                    echo "ambiente: ${ambiente}"
                    // Reemplazar {{ambiente}} en el archivo HTML
                    sh "sed 's/{{ambiente}}/${ambiente}/g' ${TEMPLATE_FILE} > ${OUTPUT_FILE}"
                }
            }
        }
        stage('Run Ansible Playbook') {
            steps {
                script {
                    sh "ansible-playbook -i ./Desafio7/ansible/${INVENTORY_FILE} ./Desafio7/ansible/main.yml -e 'environment=${env.BRANCH_NAME}'"
                }
            }
        }
    }
}
