pipeline {
    agent {label 'ansible-controller'}
    stages {
      stage('Print Environment Variables') {
            steps {
                script {
                    // Imprimir todas las variables de entorno
                    env.each { key, value ->
                        echo "${key} = ${value}"
                    }
                }
            }
        }

        stage('Validate if jenkins can execute ansible') {
            steps {
                sh '''
                ansible --version
                ansible-playbook --version
                ansible-galaxy --version
                '''
                }
        }
    }
}
