version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      
    volumes:
      - mongo-data:/data/db

  app:
    container_name: desafio10-app
    build: .
    ports:
      - "3000:3000"

    environment:
      MONGO_DB_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: app-desafio10
      MONGO_DB_USER: root
      MONGO_DB_PASS: password
    depends_on:
      - mongodb

volumes:
  mongo-data:
