
name: Build and Push Docker Image - Multiarch - Desafio9

on:
  push:
    branches: [ "main" ]
    paths: 
      - "Desafio9/**"
      - ".github/workflows/desafio9-dockerhub-push-image.yml"
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} # token dockerhub
    - run: echo " ${{ github.run_number }}"
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ github.workspace }}/Desafio9
        push: true
        tags: 1wil1/desafio9:${{ github.run_number }} # Cambia esto con tu nombre de usuario y nombre de imagen
        platforms: linux/amd64,linux/arm64,linux/arm/v7
    - name: Logout from DockerHub
      run: docker logout
